source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
use_frameworks!

pod 'GoogleMaps'
pod 'Google/CloudMessaging'
pod 'BaasBoxSDK', '~> 0.9.0'
#pod 'PKRevealController'
#pod 'SwiftyJSON'
#pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'
#pod 'ECSlidingViewController', '~> 2.0.3'
pod 'MMDrawerController', '~> 0.5.7'
xcodeproj '/Users/kishykumar/test/Example/Example.xcodeproj'
