source 'https://bitbucket.org/kishykumar/yibbypods'
source 'https://github.com/ello/cocoapod-specs.git'
source 'https://github.com/CocoaPods/Specs.git'
project '../Yibby'

platform :ios, '10.0'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

def testing_pods
    pod 'Quick'
    pod 'Nimble'
    pod 'Nimble-Snapshots'
end

def shared_pods
    pod 'FoldingCell'
    pod 'Font-Awesome-Swift'
    pod 'Alamofire'
    pod 'GoogleMaps'
    pod 'Google/CloudMessaging'
    pod 'BaasBoxSDK’
    pod 'SwiftyJSON'
    pod 'MMDrawerController'
    pod 'BButton'
    pod 'TextFieldEffects'
    pod 'ActionSheetPicker-3.0'
    pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'
    pod 'PhoneNumberKit'
    pod 'Presentr'
    pod 'KSCrash'
    pod 'MBProgressHUD'
    pod 'Cosmos'
    pod 'StepSlider'
    pod 'AMPopTip'
    pod 'LTMorphingLabel'
    pod 'M13ProgressSuite'
    pod 'CocoaLumberjack/Swift'
    pod 'LaunchScreen'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'DZNEmptyDataSet'
    pod 'PINRemoteImage'
    pod 'Stripe'
    pod 'Braintree'
    pod 'CardIO'
    pod 'XLPagerTabStrip'
    pod 'IQKeyboardManagerSwift'
    pod 'SwiftKeychainWrapper'
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
    pod 'ISHPullUp'
    pod 'AlamofireObjectMapper'
    pod 'ImagePicker'
    pod 'Lightbox'
    pod 'GoogleSignIn'
    pod 'FBSDKLoginKit'
    pod 'GooglePlaces'
    pod 'AccountKit'
    pod 'OHHTTPStubs/Swift'
    pod 'SwiftMessages'
    pod 'PasswordTextField'
    pod 'Instabug'
    pod 'AIFlatSwitch'
    pod 'Firebase/Core'
    #pod 'ReachabilitySwift', :git => 'https://github.com/ashleymills/Reachability.swift'
    #pod 'ECSlidingViewController', '~> 2.0.3'
    #pod 'PKRevealController'
end


target 'Yibby' do
    shared_pods
end

target 'YibbyTests' do
    shared_pods
    testing_pods
end


post_install do |installer|
    #installer.pods_project.targets.each do |target|
    #    target.build_configurations.each do |config|
    #        config.build_settings['SWIFT_VERSION'] = '3.0'
    #    end
    #end
    
    puts("Update debug pod settings to speed up build time")
    Dir.glob(File.join("Pods", "**", "Pods*{debug,Private}.xcconfig")).each do |file|
        File.open(file, 'a') { |f| f.puts "\nDEBUG_INFORMATION_FORMAT = dwarf" }
    end
end
