source 'https://github.com/ello/cocoapod-specs.git'
source 'https://github.com/CocoaPods/Specs.git'
xcodeproj '/Users/kishykumar/Installs/xcodeworkspace/Yibby/Yibby.xcodeproj'

platform :ios, '8.0'
use_frameworks!

def shared_pods
    pod 'GoogleMaps'
    pod 'Google/CloudMessaging'
    pod 'BaasBoxSDK’, :git => 'https://kishykumar@bitbucket.org/kishykumar/baasboxiossdk.git'
    pod 'SwiftyJSON'
    pod 'MMDrawerController', '~> 0.5.7'
    pod 'TTRangeSlider'
    pod 'BButton'
    pod 'TextFieldEffects'
    pod 'SVProgressHUD'
    pod 'ReachabilitySwift', :git => 'https://github.com/ashleymills/Reachability.swift'
    pod 'CocoaLumberjack/Swift'
    pod 'ASProgressPopUpView'
    pod 'LaunchScreen'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'DZNEmptyDataSet'
    pod 'ElloOSSUIFonts'
    pod 'SVGKit', git: 'https://github.com/SVGKit/SVGKit'
    pod 'PINRemoteImage'
    pod 'Stripe'
    pod 'Braintree'
    pod 'CardIO'
    pod 'Alamofire', '~> 3.4'
    
    #pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'
    #pod 'ECSlidingViewController', '~> 2.0.3'
    #pod 'PKRevealController'
end


target 'Yibby' do
    shared_pods
end

target 'YibbyTests' do
    shared_pods
end